### PR TITLE
pagination helpers

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@smn @miltontony ready for review.

This is almost exactly the same as unicore-cms but I changed `Paginator.total_count` to do `results.count()` instead of `len(results)` for an `S` object. I also added a `paginate` filter.

**Comment by miltontony** [comment]
:+1:

**Comment by smn** [comment]
Hm in the original implementation the `.count()` stuff was implemented in the [`EGPaginator`](https://github.com/universalcore/unicore-cms/blob/develop/cms/views/utils.py#L91-L97) subclass.

**Comment by smn** [comment]
Nothing to change here but just noting that this .count() change already existed.

**Comment by Rizziepit** [comment]
Oops, I forgot to mention that. I removed `EGPaginator` and made `Paginator` handle `S` objects instead. `EGPaginator` was doing other stuff like returning a generator that calls `to_object`. It was meant as a drop-in replacement in unicore-cms, but seemed overkill for springboard.

**Pull request merged**
