### PR TITLE
Create custom 404 page

### PR DESCRIPTION
**Pull request by nathanbegbie**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@nathanbegbie I actually fiddled with this code yesterday. Have a look at the changes I made [here](https://github.com/universalcore/unicore-cms/commit/f4e11ef98d7e7adfa210aefb145b0242ca6f1765) and [here](https://github.com/universalcore/unicore-cms/commit/b2099e894aa3addd0c5e415fc7303ca2676233f8).

Turns out the `notfound_view_config` decorator doesn't set the proper response code (surprisingly). Also, `webtest.TestApp` raises an exception when 404 is returned unless you explicitly tell it to expect an error response.

**Comment by nathanbegbie** [comment]
@Rizziepit +1 ?

**Comment by Rizziepit** [comment]
+1

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
